spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/covidukview_dev
    username: viewuser
    password: viewpass

logging:
  level:
    root: INFO
#    org.springframework.security: DEBUG
#    org.springframework.jdbc.datasource: DEBUG
#    org.springframework.jdbc.core: DEBUG
